// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tubfuecbtikoluoqixmw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR1YmZ1ZWNidGlrb2x1b3FpeG13Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ3OTQ1ODMsImV4cCI6MjA2MDM3MDU4M30.Jib47soMfllaqnMJWTakU1_1NPHBwFydS81U_3cBFTE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);